/**
 * This code was generated by [react-native-codegen](https://www.npmjs.com/package/react-native-codegen).
 *
 * Do not edit this file as changes may cause incorrect behavior and will be lost
 * once the code is regenerated.
 *
 * @generated by codegen project: GenerateModuleObjCpp
 *
 * We create an umbrella header (and corresponding implementation) here since
 * Cxx compilation in BUCK has a limitation: source-code producing genrule()s
 * must have a single output. More files => more genrule()s => slower builds.
 */

#import "RNRnRongtaPrinterSpec.h"


@implementation NativeRnRongtaPrinterSpecBase


- (void)setEventEmitterCallback:(EventEmitterCallbackWrapper *)eventEmitterCallbackWrapper
{
  _eventEmitterCallback = std::move(eventEmitterCallbackWrapper->_eventEmitterCallback);
}
@end


namespace facebook::react {
  
    static facebook::jsi::Value __hostFunction_NativeRnRongtaPrinterSpecJSI_initPrinter(facebook::jsi::Runtime& rt, TurboModule &turboModule, const facebook::jsi::Value* args, size_t count) {
      return static_cast<ObjCTurboModule&>(turboModule).invokeObjCMethod(rt, PromiseKind, "initPrinter", @selector(initPrinter:PORT:resolve:reject:), args, count);
    }

    static facebook::jsi::Value __hostFunction_NativeRnRongtaPrinterSpecJSI_multiply(facebook::jsi::Runtime& rt, TurboModule &turboModule, const facebook::jsi::Value* args, size_t count) {
      return static_cast<ObjCTurboModule&>(turboModule).invokeObjCMethod(rt, NumberKind, "multiply", @selector(multiply:b:), args, count);
    }

    static facebook::jsi::Value __hostFunction_NativeRnRongtaPrinterSpecJSI_doDisConnect(facebook::jsi::Runtime& rt, TurboModule &turboModule, const facebook::jsi::Value* args, size_t count) {
      return static_cast<ObjCTurboModule&>(turboModule).invokeObjCMethod(rt, PromiseKind, "doDisConnect", @selector(doDisConnect:reject:), args, count);
    }

    static facebook::jsi::Value __hostFunction_NativeRnRongtaPrinterSpecJSI_tscPrint(facebook::jsi::Runtime& rt, TurboModule &turboModule, const facebook::jsi::Value* args, size_t count) {
      return static_cast<ObjCTurboModule&>(turboModule).invokeObjCMethod(rt, PromiseKind, "tscPrint", @selector(tscPrint:width:height:resolve:reject:), args, count);
    }

    static facebook::jsi::Value __hostFunction_NativeRnRongtaPrinterSpecJSI_print(facebook::jsi::Runtime& rt, TurboModule &turboModule, const facebook::jsi::Value* args, size_t count) {
      return static_cast<ObjCTurboModule&>(turboModule).invokeObjCMethod(rt, PromiseKind, "print", @selector(print:resolve:reject:), args, count);
    }

  NativeRnRongtaPrinterSpecJSI::NativeRnRongtaPrinterSpecJSI(const ObjCTurboModule::InitParams &params)
    : ObjCTurboModule(params) {
      
        methodMap_["initPrinter"] = MethodMetadata {2, __hostFunction_NativeRnRongtaPrinterSpecJSI_initPrinter};
        
        
        methodMap_["multiply"] = MethodMetadata {2, __hostFunction_NativeRnRongtaPrinterSpecJSI_multiply};
        
        
        methodMap_["doDisConnect"] = MethodMetadata {0, __hostFunction_NativeRnRongtaPrinterSpecJSI_doDisConnect};
        
        
        methodMap_["tscPrint"] = MethodMetadata {3, __hostFunction_NativeRnRongtaPrinterSpecJSI_tscPrint};
        
        
        methodMap_["print"] = MethodMetadata {1, __hostFunction_NativeRnRongtaPrinterSpecJSI_print};
        
  }
} // namespace facebook::react
