/**
 * This code was generated by [react-native-codegen](https://www.npmjs.com/package/react-native-codegen).
 *
 * Do not edit this file as changes may cause incorrect behavior and will be lost
 * once the code is regenerated.
 *
 * @generated by codegen project: GenerateModuleCpp.js
 */

#include "RNRnRongtaPrinterSpecJSI.h"

namespace facebook::react {

static jsi::Value __hostFunction_NativeRnRongtaPrinterCxxSpecJSI_initPrinter(jsi::Runtime &rt, TurboModule &turboModule, const jsi::Value* args, size_t count) {
  return static_cast<NativeRnRongtaPrinterCxxSpecJSI *>(&turboModule)->initPrinter(
    rt,
    count <= 0 ? throw jsi::JSError(rt, "Expected argument in position 0 to be passed") : args[0].asString(rt),
    count <= 1 ? throw jsi::JSError(rt, "Expected argument in position 1 to be passed") : args[1].asNumber()
  );
}
static jsi::Value __hostFunction_NativeRnRongtaPrinterCxxSpecJSI_multiply(jsi::Runtime &rt, TurboModule &turboModule, const jsi::Value* args, size_t count) {
  return static_cast<NativeRnRongtaPrinterCxxSpecJSI *>(&turboModule)->multiply(
    rt,
    count <= 0 ? throw jsi::JSError(rt, "Expected argument in position 0 to be passed") : args[0].asNumber(),
    count <= 1 ? throw jsi::JSError(rt, "Expected argument in position 1 to be passed") : args[1].asNumber()
  );
}
static jsi::Value __hostFunction_NativeRnRongtaPrinterCxxSpecJSI_doDisConnect(jsi::Runtime &rt, TurboModule &turboModule, const jsi::Value* args, size_t count) {
  return static_cast<NativeRnRongtaPrinterCxxSpecJSI *>(&turboModule)->doDisConnect(
    rt
  );
}
static jsi::Value __hostFunction_NativeRnRongtaPrinterCxxSpecJSI_tscPrint(jsi::Runtime &rt, TurboModule &turboModule, const jsi::Value* args, size_t count) {
  return static_cast<NativeRnRongtaPrinterCxxSpecJSI *>(&turboModule)->tscPrint(
    rt,
    count <= 0 ? throw jsi::JSError(rt, "Expected argument in position 0 to be passed") : args[0].asString(rt),
    count <= 1 ? throw jsi::JSError(rt, "Expected argument in position 1 to be passed") : args[1].asNumber(),
    count <= 2 ? throw jsi::JSError(rt, "Expected argument in position 2 to be passed") : args[2].asNumber()
  );
}
static jsi::Value __hostFunction_NativeRnRongtaPrinterCxxSpecJSI_print(jsi::Runtime &rt, TurboModule &turboModule, const jsi::Value* args, size_t count) {
  return static_cast<NativeRnRongtaPrinterCxxSpecJSI *>(&turboModule)->print(
    rt,
    count <= 0 ? throw jsi::JSError(rt, "Expected argument in position 0 to be passed") : args[0].asString(rt)
  );
}

NativeRnRongtaPrinterCxxSpecJSI::NativeRnRongtaPrinterCxxSpecJSI(std::shared_ptr<CallInvoker> jsInvoker)
  : TurboModule("RnRongtaPrinter", jsInvoker) {
  methodMap_["initPrinter"] = MethodMetadata {2, __hostFunction_NativeRnRongtaPrinterCxxSpecJSI_initPrinter};
  methodMap_["multiply"] = MethodMetadata {2, __hostFunction_NativeRnRongtaPrinterCxxSpecJSI_multiply};
  methodMap_["doDisConnect"] = MethodMetadata {0, __hostFunction_NativeRnRongtaPrinterCxxSpecJSI_doDisConnect};
  methodMap_["tscPrint"] = MethodMetadata {3, __hostFunction_NativeRnRongtaPrinterCxxSpecJSI_tscPrint};
  methodMap_["print"] = MethodMetadata {1, __hostFunction_NativeRnRongtaPrinterCxxSpecJSI_print};
}


} // namespace facebook::react
